"""
Django settings for note_backend project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Django projenizin gizli anahtarını içeren değişken.
SECRET_KEY = 'django-insecure-7y6s096h&bk%*#k_sd!e5yi#*$3)97y&u957$bzso7k^5=8tz*'

# Geliştirme modu: True (Üretimde False olarak ayarlanmalıdır.)
DEBUG = True

# Django uygulamanızın hangi hostlardan gelen istekleri kabul edeceğini belirler.
ALLOWED_HOSTS = []

# Django REST framework ayarları
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Herkese izin verme (daha güvenli ayarlar yapmalısınız)
    ],
}

# CORS ayarları: React uygulamanızın çalıştığı adresi ekleyin.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

# Etkinleştirilmiş uygulamaların listesi
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "notes",
    'rest_framework',
    'corsheaders',
]

# Ara yazılım bileşenleri
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

# Django projenizin URL yapılandırması
ROOT_URLCONF = 'note_backend.urls'

# Django şablon ayarları
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI uygulaması
WSGI_APPLICATION = 'note_backend.wsgi.application'

# Veritabanı bağlantı ayarları (Varsayılan olarak SQLite kullanılır.)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Parola doğrulama ayarları
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Dil ve zaman dilimi ayarları
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Statik dosyaların URL'si
STATIC_URL = 'static/'

# Otomatik oluşturulan model alanı türü
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
